services:
  fleetspeak-db:
    image: mysql:8.2
    restart: always
    hostname: fleetspeak-db
    environment:
      MYSQL_DATABASE: 'fleetspeak'
      MYSQL_USER: 'fleetspeak-user'
      MYSQL_PASSWORD: 'fleetspeak-password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  fleetspeak-server:
    build:
      context: ../
      dockerfile: ./Dockerfile.dev
    hostname: fleetspeak-test
    depends_on:
      fleetspeak-db:
        condition: service_healthy
    entrypoint: ["tail", "-F", "/fleetspeak/spanner-setup/setup.sh"]
    volumes:
      - "/home/user/.config/gcloud/:/root/.config/gcloud"

volumes:
  db_data:
networks:
  server-network:
